// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6cUArxkj_qpYXKBr5kt5fUVTLxBCkvNw',
    appId: '1:897866685307:web:89c087afe2e94a69303bde',
    messagingSenderId: '897866685307',
    projectId: 'personal-chat-2e22c',
    authDomain: 'personal-chat-2e22c.firebaseapp.com',
    storageBucket: 'personal-chat-2e22c.appspot.com',
    measurementId: 'G-WQEELZ1JK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzt2KPKlG5mbe8sAFuaTI3tSNP6wZsdck',
    appId: '1:897866685307:android:bdee5021765817c8303bde',
    messagingSenderId: '897866685307',
    projectId: 'personal-chat-2e22c',
    storageBucket: 'personal-chat-2e22c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCU359LyjZI8EECXOtu5Q7_EAAkWg7k_k',
    appId: '1:897866685307:ios:cff38480eb649400303bde',
    messagingSenderId: '897866685307',
    projectId: 'personal-chat-2e22c',
    storageBucket: 'personal-chat-2e22c.appspot.com',
    iosBundleId: 'com.example.personalChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCU359LyjZI8EECXOtu5Q7_EAAkWg7k_k',
    appId: '1:897866685307:ios:cff38480eb649400303bde',
    messagingSenderId: '897866685307',
    projectId: 'personal-chat-2e22c',
    storageBucket: 'personal-chat-2e22c.appspot.com',
    iosBundleId: 'com.example.personalChat',
  );
}
